"""Shared helpers for the STREET_KIT family builders (bpy 5.0.1 from PyPI or Blender 5.x, background mode).

Conventions (same as VAN-TIER0-ASTRA-001 / WATER-TOWER-ASTRA-001):
  * Blender Z up, metres, -Y is the front of a piece; FBX axis_forward=-Z, axis_up=Y, apply_unit_scale=True.
  * Every asset is built at the world origin under a root empty SK_<Asset>; pivot = centre of the base on the ground.
    Wall-mounted pieces (balconies, AC units, dishes, drainpipes) have the pivot on the wall plane, see family README.
    Moving parts (lids, swing seats, carousel, barrier boom) are child meshes with the pivot on their hinge/axis.
  * One shared palette material SK_Palette for everything: every face gets a UV point in the centre of its colour
    cell of the 8x4 palette texture SK_Palette.png (16 px cells, generated by this module) AND the same colour as
    a corner vertex colour 'Col'. Shop-sign faces use the second material SK_Signage with UVs into the signage atlas.
  * Faceted (flat) shading; every shell closed and outward facing.
  * Per asset: <Asset>_vNN.fbx and validation_<Asset>_vNN.json; per family: SK-<FAMILY>_vNN.blend and Previews/vNN/.
  * Existing revisions are never overwritten unless --force is passed.
"""
import argparse, json, math, sys
from pathlib import Path

import bpy, bmesh
from mathutils import Vector, Matrix

TAU = math.tau
LIB_DIR = Path(__file__).resolve().parent
KIT_DIR = LIB_DIR.parent

# ---------------------------------------------------------------- palette (sRGB 0-255), 8 x 4 cells, index = row * 8 + col
PALETTE = [
    ('concrete', (156, 152, 142)), ('concrete_dark', (120, 118, 112)), ('wood', (164, 112, 64)), ('wood_dark', (106, 74, 46)),
    ('green', (78, 132, 88)), ('blue', (74, 118, 168)), ('red', (204, 62, 50)), ('yellow', (240, 194, 58)),
    ('orange', (232, 124, 46)), ('white', (236, 234, 226)), ('metal_dark', (54, 56, 62)), ('metal', (132, 136, 142)),
    ('black', (28, 29, 32)), ('rust', (128, 66, 38)), ('glass', (110, 150, 168)), ('glass_dark', (44, 58, 70)),
    ('sign_blue', (30, 90, 176)), ('sign_red', (210, 36, 40)), ('sand', (226, 202, 150)), ('brick', (162, 84, 62)),
    ('soot', (38, 34, 32)), ('ash', (112, 106, 100)), ('car_blue', (124, 168, 176)), ('cream', (226, 214, 176)),
    ('rubber', (40, 40, 44)), ('bag', (52, 60, 54)), ('teal', (52, 160, 156)), ('purple', (132, 92, 160)),
    ('glow', (255, 228, 160)), ('chrome', (190, 194, 198)), ('dirt', (124, 104, 78)), ('pink', (222, 120, 140)),
]
PAL = {n: i for i, (n, _) in enumerate(PALETTE)}
PAL_COLS, PAL_ROWS, PAL_CELL = 8, 4, 16

# ---------------------------------------------------------------- signage atlas (2048 x 2048, 256 px per metre of board)
ATLAS_PX = 2048
SIGN_TYPES = {
    # type: (cell w px, cell h px, origin x px, origin y px (from the top), columns, rows)
    'wide_4x1':     (1024, 256, 0, 0, 2, 4),        # 4.0 x 1.0 m boards and kiosk / ATM bands
    'medium_2x1':   (512, 256, 0, 1024, 4, 2),      # 2.0 x 1.0 m boards
    'square_1x1':   (256, 256, 0, 1536, 4, 2),      # projecting lightboxes
    'vertical_1x4': (128, 512, 1024, 1536, 8, 1),   # projecting vertical boards
}


def sign_uv_rect(kind, slot=0):
    """(u0, v0, u1, v1) of a signage atlas slot; v measured upwards as in Blender/Unity."""
    w, h, ox, oy, cols, rows = SIGN_TYPES[kind]
    c, r = slot % cols, slot // cols
    x0, y0 = ox + c * w, oy + r * h
    return (x0 / ATLAS_PX, 1 - (y0 + h) / ATLAS_PX, (x0 + w) / ATLAS_PX, 1 - y0 / ATLAS_PX)


def atlas_layout():
    return {k: {'cell_px': [v[0], v[1]], 'slots': [list(round(x, 6) for x in sign_uv_rect(k, s)) for s in range(v[4] * v[5])]}
            for k, v in SIGN_TYPES.items()}


def srgb_to_linear(c):
    return tuple(((v / 255) / 12.92 if v / 255 <= 0.04045 else ((v / 255 + 0.055) / 1.055) ** 2.4) for v in c)


def pal_uv(name):
    i = PAL[name]
    return ((i % PAL_COLS + 0.5) / PAL_COLS, 1 - (i // PAL_COLS + 0.5) / PAL_ROWS)


# ---------------------------------------------------------------- matrices
def T(x=0.0, y=0.0, z=0.0):
    return Matrix.Translation((x, y, z))


def R(deg, axis):
    return Matrix.Rotation(math.radians(deg), 4, axis)


def S(x, y=None, z=None):
    return Matrix.Diagonal((x, x if y is None else y, x if z is None else z, 1.0))


# ---------------------------------------------------------------- mesh accumulator
class Mesh:
    """Closed shells as plain lists. faces: vertex index tuples; fcol: palette name per face; fuv: optional per-loop UVs
    (signage faces) or None."""

    def __init__(self):
        self.verts, self.faces, self.fcol, self.fuv = [], [], [], []

    def shell(self, verts, faces, col, M=None, cols=None, uvs=None):
        M = M or Matrix.Identity(4)
        b = len(self.verts)
        self.verts += [tuple(M @ Vector(v)) for v in verts]
        for i, f in enumerate(faces):
            self.faces.append(tuple(b + k for k in f))
            self.fcol.append(cols[i] if cols and cols[i] else col)
            self.fuv.append(uvs[i] if uvs else None)
        return range(len(self.faces) - len(faces), len(self.faces))

    def merge(self, other, M=None):
        self.shell(other.verts, [tuple(f) for f in other.faces], None, M, cols=other.fcol, uvs=other.fuv)

    def tris(self):
        return sum(len(f) - 2 for f in self.faces)

    # -- primitives (all closed)
    def box(self, sx, sy, sz, col, M=None, at=(0, 0, 0), base=False, top=None, bottom=None):
        """Axis box centred at `at` (or standing on `at` when base=True); top/bottom: optional cap colours."""
        x, y = sx / 2, sy / 2
        z0, z1 = (0, sz) if base else (-sz / 2, sz / 2)
        v = [(-x, -y, z0), (x, -y, z0), (x, y, z0), (-x, y, z0), (-x, -y, z1), (x, -y, z1), (x, y, z1), (-x, y, z1)]
        f = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
        cols = [bottom, top, None, None, None, None]
        return self.shell(v, f, col, (M or Matrix.Identity(4)) @ T(*at), cols=cols)

    def bevel_box(self, sx, sy, sz, bev, col, M=None, at=(0, 0, 0), base=False):
        """Chamfered box (one 45-degree bevel on every edge): 26 faces, 44 triangles - reads chunky and cartoon."""
        bm = bmesh.new()
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=(sx, sy, sz), verts=bm.verts)
        bmesh.ops.bevel(bm, geom=list(bm.edges), offset=min(bev, sx / 2.01, sy / 2.01, sz / 2.01), segments=1,
                        affect='EDGES', profile=0.5)
        if base:
            bmesh.ops.translate(bm, vec=(0, 0, sz / 2), verts=bm.verts)
        v = [tuple(x.co) for x in bm.verts]
        bm.verts.index_update()
        f = [tuple(x.index for x in fa.verts) for fa in bm.faces]
        bm.free()
        return self.shell(v, f, col, (M or Matrix.Identity(4)) @ T(*at))

    def prism(self, poly, d, col, M=None, side=None, cap=None):
        """Convex or star-shaped polygon in the XZ plane, extruded along Y from -d/2 to +d/2 (front cap faces -Y)."""
        n = len(poly)
        if sum((poly[(i + 1) % n][0] - poly[i][0]) * (poly[(i + 1) % n][1] + poly[i][1]) for i in range(n)) > 0:
            poly = poly[::-1]                       # make it counter-clockwise seen from -Y
        v = [(x, -d / 2, z) for x, z in poly] + [(x, d / 2, z) for x, z in poly]
        f = [tuple(range(n)), tuple(range(2 * n - 1, n - 1, -1))]
        cols = [cap, cap]
        for i in range(n):
            j = (i + 1) % n
            f.append((i, n + i, n + j, j))
            cols.append(side)
        return self.shell(v, f, col, M, cols=cols)

    def prism_xy(self, poly, z0, z1, col, M=None, top=None):
        """Polygon in the XY plane extruded from z0 to z1."""
        n = len(poly)
        if sum((poly[(i + 1) % n][0] - poly[i][0]) * (poly[(i + 1) % n][1] + poly[i][1]) for i in range(n)) > 0:
            poly = poly[::-1]                       # counter-clockwise seen from +Z
        v = [(x, y, z0) for x, y in poly] + [(x, y, z1) for x, y in poly]
        f = [tuple(range(n - 1, -1, -1)), tuple(range(n, 2 * n))]
        cols = [None, top]
        for i in range(n):
            j = (i + 1) % n
            f.append((i, j, n + j, n + i))
            cols.append(None)
        return self.shell(v, f, col, M, cols=cols)

    def lathe(self, profile, seg, col, M=None, offset=0.0, cols=None):
        """profile: [(r, z)] bottom to top; r == 0 collapses to a pole. Closed with caps where r > 0 at the ends."""
        v, f, fc = [], [], []
        rings = []
        for r, z in profile:
            if r <= 1e-9:
                rings.append([len(v)]); v.append((0, 0, z))
            else:
                rings.append(list(range(len(v), len(v) + seg)))
                v += [(r * math.cos(offset + TAU * k / seg), r * math.sin(offset + TAU * k / seg), z) for k in range(seg)]
        for b, (a, c) in enumerate(zip(rings, rings[1:])):
            bc = cols[b] if cols else None
            for k in range(seg):
                k1 = (k + 1) % seg
                if len(a) == 1:
                    f.append((a[0], c[k1], c[k]))
                elif len(c) == 1:
                    f.append((a[k], a[k1], c[0]))
                else:
                    f.append((a[k], a[k1], c[k1], c[k]))
                fc.append(bc)
        if len(rings[0]) > 1:
            f.append(tuple(reversed(rings[0]))); fc.append(cols[0] if cols else None)
        if len(rings[-1]) > 1:
            f.append(tuple(rings[-1])); fc.append(cols[-1] if cols else None)
        return self.shell(v, f, col, M, cols=fc)

    def cyl(self, r, h, seg, col, M=None, r_top=None, at=(0, 0, 0), offset=None):
        """Upright cylinder / frustum standing on `at`."""
        off = math.pi / seg if offset is None else offset
        return self.lathe([(r, 0), (r if r_top is None else r_top, h)], seg, col, (M or Matrix.Identity(4)) @ T(*at), off)

    def bar(self, p0, p1, r, col, seg=6, r1=None):
        """Cylinder from p0 to p1 (round tube, rung, chain, pipe)."""
        p0, p1 = Vector(p0), Vector(p1)
        d = p1 - p0
        q = d.to_track_quat('Z', 'Y' if abs(d.normalized().z) < 0.99 else 'X')
        M = T(*p0) @ q.to_matrix().to_4x4()
        return self.cyl(r, d.length, seg, col, M, r_top=r1, offset=math.pi / seg)

    def beam(self, p0, p1, w, h, col, up=(0, 0, 1)):
        """Box from p0 to p1 with cross-section w (sideways) x h (along `up`)."""
        p0, p1 = Vector(p0), Vector(p1)
        d = p1 - p0
        x = d.normalized()
        z = Vector(up)
        z = (z - x * z.dot(x)).normalized()
        y = z.cross(x)
        M = Matrix((x, y, z)).transposed().to_4x4()
        M.translation = (p0 + p1) / 2
        return self.box(d.length, w, h, col, M)

    def tube_path(self, pts, r, seg, col, closed=False):
        """Swept round tube through points (mitred joints) - bent pipes, swing frames, handrails."""
        pts = [Vector(p) for p in pts]
        n = len(pts)
        rings = []
        a = None
        for i, p in enumerate(pts):
            if closed:
                t = (pts[(i + 1) % n] - pts[i - 1]).normalized()
            elif i == 0:
                t = (pts[1] - pts[0]).normalized()
            elif i == n - 1:
                t = (pts[-1] - pts[-2]).normalized()
            else:
                t = ((pts[i + 1] - p).normalized() + (p - pts[i - 1]).normalized()).normalized()
            if a is None:
                ref = Vector((0, 0, 1)) if abs(t.z) < 0.9 else Vector((1, 0, 0))
                a = t.cross(ref).normalized()
            else:
                a = (a - t * a.dot(t)).normalized()          # parallel transport: no twist between rings
            b = t.cross(a)
            scale = 1.0
            if 0 < i < n - 1 or closed:
                d0 = (p - pts[i - 1]).normalized()
                scale = 1 / max(0.5, d0.dot(t))
            rings.append([p + (a * math.cos(TAU * k / seg + math.pi / seg) + b * math.sin(TAU * k / seg + math.pi / seg)) * r * scale
                          for k in range(seg)])
        v = [tuple(x) for ring in rings for x in ring]
        f = []
        m = n if closed else n - 1
        for i in range(m):
            a0, b0 = i * seg, ((i + 1) % n) * seg
            for k in range(seg):
                k1 = (k + 1) % seg
                f.append((a0 + k, a0 + k1, b0 + k1, b0 + k))
        if not closed:
            f.append(tuple(range(seg - 1, -1, -1)))
            f.append(tuple(range((n - 1) * seg, n * seg)))
        return self.shell(v, f, col)

    def sign_face_box(self, w, h, d, frame_col, kind, slot=0, M=None, both=False):
        """Board w x h (XZ) x d deep, centred; its -Y face (and +Y when both) is a signage face mapped to an atlas slot."""
        u0, v0, u1, v1 = sign_uv_rect(kind, slot)
        fs = self.box(w, d, h, frame_col, M)
        faces = list(fs)
        # face order from box(): bottom, top, -Y, +X, +Y, -X
        front, back = faces[2], faces[4]
        self.fuv[front] = [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]          # loop order (0,1,5,4): BL, BR, TR, TL
        if both:
            self.fuv[back] = [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]       # loop order (2,3,7,6): from +Y also BL..TL
        return fs


def jitter(mesh, amount, seed, start=0, keep_ground=True):
    """Deterministic vertex noise for dents / wobble (vertices on z == 0 stay on the ground)."""
    import random
    rnd = random.Random(seed)
    for i in range(start, len(mesh.verts)):
        x, y, z = mesh.verts[i]
        dz = 0 if keep_ground and abs(z) < 1e-6 else rnd.uniform(-amount, amount)
        z = z + dz
        if keep_ground:
            z = max(z, 0.0)
        mesh.verts[i] = (x + rnd.uniform(-amount, amount), y + rnd.uniform(-amount, amount), z)


# ---------------------------------------------------------------- materials and textures
_MATS = {}


def palette_image():
    img = bpy.data.images.get('SK_Palette')
    if img:
        return img
    W, H = PAL_COLS * PAL_CELL, PAL_ROWS * PAL_CELL
    img = bpy.data.images.new('SK_Palette', W, H, alpha=False)
    img.colorspace_settings.name = 'sRGB'                   # byte image: pixels hold sRGB-encoded values / 255
    px = [0.0] * (W * H * 4)
    for y in range(H):
        row = PAL_ROWS - 1 - y // PAL_CELL                  # image rows go bottom-up
        for x in range(W):
            c = [v / 255 for v in PALETTE[row * PAL_COLS + x // PAL_CELL][1]]
            o = (y * W + x) * 4
            px[o:o + 4] = [*c, 1.0]
    img.pixels = px
    return img


def atlas_placeholder_image():
    """Grey placeholder signage atlas: every slot type tinted, slot borders dark - only for previews."""
    img = bpy.data.images.get('SK_SignageAtlas_Placeholder')
    if img:
        return img
    N = 256
    img = bpy.data.images.new('SK_SignageAtlas_Placeholder', N, N, alpha=False)
    px = [0.25] * (N * N * 4)
    tints = {'wide_4x1': (0.85, 0.80, 0.55), 'medium_2x1': (0.60, 0.80, 0.85), 'square_1x1': (0.85, 0.65, 0.60),
             'vertical_1x4': (0.70, 0.85, 0.60)}
    for kind, (w, h, ox, oy, cols, rows) in SIGN_TYPES.items():
        for s in range(cols * rows):
            u0, v0, u1, v1 = sign_uv_rect(kind, s)
            X0, X1, Y0, Y1 = int(u0 * N), int(u1 * N), int(v0 * N), int(v1 * N)
            for y in range(Y0, Y1):
                for x in range(X0, X1):
                    edge = x - X0 < 2 or X1 - x <= 2 or y - Y0 < 2 or Y1 - y <= 2
                    stripe = (Y1 - Y0) > 8 and abs((y - Y0) - (Y1 - Y0) // 2) < max(1, (Y1 - Y0) // 10) and 0.2 < (x - X0) / max(1, X1 - X0) < 0.8
                    c = (0.08, 0.08, 0.1) if edge else ((0.15, 0.15, 0.18) if stripe else tints[kind])
                    o = (y * N + x) * 4
                    px[o:o + 4] = [*c, 1.0]
    img.pixels = px
    return img


def _image_material(name, img, rough):
    if name in _MATS:
        return _MATS[name]
    m = bpy.data.materials.new(name)
    try:
        m.use_nodes = True
    except Exception:
        pass
    nt = m.node_tree
    b = next(n for n in nt.nodes if n.type == 'BSDF_PRINCIPLED')
    tex = nt.nodes.new('ShaderNodeTexImage')
    tex.image = img
    tex.interpolation = 'Closest'
    nt.links.new(tex.outputs['Color'], b.inputs['Base Color'])
    b.inputs['Roughness'].default_value = rough
    if 'Specular IOR Level' in b.inputs:
        b.inputs['Specular IOR Level'].default_value = 0.2
    m.diffuse_color = (0.6, 0.6, 0.6, 1.0)
    _MATS[name] = m
    return m


def palette_material():
    return _image_material('SK_Palette', palette_image(), 0.85)


def signage_material():
    return _image_material('SK_Signage', atlas_placeholder_image(), 0.6)


def save_textures(out_dir):
    """Writes SK_Palette.png (128 x 64) next to the library; the signage placeholder stays inside the .blend only."""
    img = palette_image()
    p = Path(out_dir) / 'SK_Palette.png'
    img.filepath_raw = str(p)
    img.file_format = 'PNG'
    img.save()
    return p


# ---------------------------------------------------------------- family / asset management
class Family:
    def __init__(self, family_id, script_file, description=''):
        ap = argparse.ArgumentParser()
        ap.add_argument('--revision', type=int, default=1)
        ap.add_argument('--no-render', action='store_true')
        ap.add_argument('--force', action='store_true', help='overwrite an existing revision')
        ap.add_argument('--samples', type=int, default=24)
        ap.add_argument('--only', default='', help='comma separated asset names (debug; skips the family .blend)')
        argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
        self.args, _ = ap.parse_known_args(argv)
        self.id = family_id
        self.description = description
        self.dir = Path(script_file).resolve().parent
        self.rev = f'v{self.args.revision:02d}'
        self.blend_path = self.dir / f'{family_id}_{self.rev}.blend'
        self.preview_dir = self.dir / 'Previews' / self.rev
        self.only = {s for s in self.args.only.split(',') if s}
        if not self.args.force:
            existing = [p for p in [self.blend_path, *self.dir.glob(f'*_{self.rev}.fbx'), *self.dir.glob(f'validation_*_{self.rev}.json')]
                        if p.exists()]
            if existing:
                sys.exit(f'Refusing to overwrite existing {existing[0].name}; choose a new --revision or pass --force')
        bpy.ops.wm.read_factory_settings(use_empty=True)
        bpy.context.preferences.filepaths.save_version = 0      # no .blend1 backups next to the deliverables
        self.scene = bpy.context.scene
        self.scene.unit_settings.system = 'METRIC'
        self.scene.unit_settings.scale_length = 1.0
        self.assets = []
        self.report = {}

    def wants(self, name):
        return not self.only or name in self.only

    # -- objects
    def make_object(self, name, mesh, coll, parent=None, pivot=(0, 0, 0)):
        """Mesh object whose origin sits at `pivot` (world coords); vertices are given in world coords."""
        pv = Vector(pivot)
        me = bpy.data.meshes.new(name)
        me.from_pydata([tuple(Vector(v) - pv) for v in mesh.verts], [], [list(f) for f in mesh.faces])
        has_sign = any(u is not None for u in mesh.fuv)
        me.materials.append(palette_material())
        if has_sign:
            me.materials.append(signage_material())
        me.uv_layers.new(name='UVMap')
        me.color_attributes.new('Col', 'BYTE_COLOR', 'CORNER')
        uvs, cols, mats = [], [], []
        for p in me.polygons:
            i = p.index
            sign = mesh.fuv[i]
            mats.append(1 if sign else 0)
            col = mesh.fcol[i] or 'concrete'
            c = (*srgb_to_linear(PALETTE[PAL[col]][1]), 1.0) if not sign else (1.0, 1.0, 1.0, 1.0)
            for k in range(p.loop_total):
                uvs += sign[k] if sign else pal_uv(col)
                cols += c
        me.polygons.foreach_set('material_index', mats)
        me.polygons.foreach_set('use_smooth', [False] * len(mats))
        me.uv_layers['UVMap'].data.foreach_set('uv', uvs)
        me.color_attributes['Col'].data.foreach_set('color', cols)
        me.update()
        ob = bpy.data.objects.new(name, me)
        coll.objects.link(ob)
        ob.location = pv
        if parent:
            ob.parent = parent
            ob.matrix_parent_inverse = parent.matrix_world.inverted()
        return ob

    def asset(self, name, parts, budget=(100, 1500), sockets=(), notes='', ground=True, wall_mounted=False):
        """parts: [(object name, Mesh, pivot or None, local rotation euler deg or None)] - the first is the main body.
        Creates collection + root empty SK_<name> at the origin; everything is parented to the root."""
        coll = bpy.data.collections.new(name)
        self.scene.collection.children.link(coll)
        root = bpy.data.objects.new(name, None)
        root.empty_display_type = 'PLAIN_AXES'
        root.empty_display_size = 0.3
        coll.objects.link(root)
        objs = []
        for pname, mesh, pivot, rot in parts:
            ob = self.make_object(pname, mesh, coll, root, pivot or (0, 0, 0))
            if rot:
                ob.rotation_euler = [math.radians(a) for a in rot]
            objs.append(ob)
        socks = []
        for sname, pos in sockets:
            e = bpy.data.objects.new(f'{name}_{sname}', None)        # asset-prefixed: Blender names are global
            e.empty_display_type = 'ARROWS'
            e.empty_display_size = 0.15
            e.location = pos
            coll.objects.link(e)
            e.parent = root
            socks.append(e)
        self.assets.append({'name': name, 'root': root, 'objects': objs, 'sockets': socks, 'coll': coll,
                            'budget': budget, 'notes': notes, 'ground': ground, 'wall': wall_mounted})
        return root

    # -- validation
    @staticmethod
    def analyse(ob):
        bm = bmesh.new()
        bm.from_mesh(ob.data)
        bm.normal_update()
        tris = sum(len(f.verts) - 2 for f in bm.faces)
        nonman = sum(1 for e in bm.edges if not e.is_manifold)
        boundary = sum(1 for e in bm.edges if e.is_boundary)
        before = [f.normal.copy() for f in bm.faces]
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        bm.normal_update()
        flipped = sum(1 for f, n in zip(bm.faces, before) if f.normal.dot(n) < 0)
        zero = sum(1 for f in bm.faces if f.calc_area() < 1e-7)
        bm.free()
        return {'triangles': tris, 'vertices': len(ob.data.vertices), 'faces': len(ob.data.polygons),
                'materials': [m.name for m in ob.data.materials],
                'pivot_local': [round(v, 4) for v in ob.location],
                'non_manifold_edges': nonman, 'boundary_edges': boundary, 'flipped_faces': flipped, 'zero_area_faces': zero}

    def validate(self, a):
        bpy.context.view_layer.update()
        objs = {o.name: self.analyse(o) for o in a['objects']}
        pts = [o.matrix_world @ Vector(c) for o in a['objects'] for c in o.bound_box]
        lo = [min(p[i] for p in pts) for i in range(3)]
        hi = [max(p[i] for p in pts) for i in range(3)]
        total = sum(v['triangles'] for v in objs.values())
        b0, b1 = a['budget']
        checks = {
            'triangle_budget_%d_%d' % (b0, b1): b0 <= total <= b1,
            'closed_manifold': all(v['non_manifold_edges'] == 0 and v['boundary_edges'] == 0 for v in objs.values()),
            'consistent_normals': all(v['flipped_faces'] == 0 for v in objs.values()),
            'no_zero_area_faces': all(v['zero_area_faces'] == 0 for v in objs.values()),
            'root_at_origin': tuple(a['root'].location) == (0.0, 0.0, 0.0),
        }
        if a['ground']:
            checks['base_on_ground_z0'] = abs(lo[2]) < 0.005
        rep = {
            'asset': a['name'], 'family': self.id, 'revision': self.rev,
            'blender': bpy.app.version_string,
            'axes': 'Blender Z up, -Y front, metres; FBX axis_forward=-Z, axis_up=Y, apply_unit_scale=True',
            'pivot': ('root empty at (0,0,0) = wall attachment point, see README' if a['wall']
                      else 'root empty at (0,0,0) = centre of the base on the ground'),
            'triangles_total': total, 'triangle_budget': [b0, b1],
            'bounds_min': [round(v, 4) for v in lo], 'bounds_max': [round(v, 4) for v in hi],
            'size_xyz_m': [round(hi[i] - lo[i], 3) for i in range(3)],
            'objects': objs,
            'sockets': {s.name: [round(v, 4) for v in s.matrix_world.translation] for s in a['sockets']},
            'materials': sorted({m for v in objs.values() for m in v['materials']}),
            'palette': 'SK_Palette.png 8x4 cells x 16 px, UV0 points at cell centres; vertex colour "Col" carries the same colour',
            'notes': a['notes'],
            'checks': checks, 'all_checks_passed': all(checks.values()),
        }
        if 'SK_Signage' in rep['materials']:
            rep['signage_atlas'] = 'SK_Signage: 2048x2048 atlas, 256 px per metre, layout in _lib/signage_atlas_layout.json'
        return rep

    # -- output
    def finish(self, gap=1.0):
        rev = self.rev
        # lay assets out in a row for the review .blend (roots are moved, then restored to the origin before export)
        out = {}
        for a in self.assets:
            rep = self.validate(a)
            fbx = self.dir / f'{a["name"]}_{rev}.fbx'
            bpy.ops.object.select_all(action='DESELECT')
            for o in [a['root'], *a['objects'], *a['sockets']]:
                o.select_set(True)
            bpy.context.view_layer.objects.active = a['root']
            bpy.ops.export_scene.fbx(filepath=str(fbx), use_selection=True, object_types={'EMPTY', 'MESH'},
                                     axis_forward='-Z', axis_up='Y', apply_unit_scale=True, use_mesh_modifiers=False,
                                     mesh_smooth_type='FACE', add_leaf_bones=False, bake_anim=False, colors_type='SRGB',
                                     path_mode='STRIP')
            rep['files'] = {'fbx': fbx.name, 'fbx_size_bytes': fbx.stat().st_size, 'blend': self.blend_path.name}
            (self.dir / f'validation_{a["name"]}_{rev}.json').write_text(json.dumps(rep, indent=2, ensure_ascii=False), encoding='utf-8')
            out[a['name']] = rep
            flag = 'OK ' if rep['all_checks_passed'] else 'FAIL'
            print(f'[SK] {flag} {a["name"]:34s} tris {rep["triangles_total"]:5d}  size {rep["size_xyz_m"]}  '
                  + ' '.join(k for k, v in rep['checks'].items() if not v))
        self.report = out
        # review layout
        x = 0.0
        for a in self.assets:
            w = out[a['name']]['size_xyz_m'][0]
            lo = out[a['name']]['bounds_min'][0]
            a['root'].location.x = x - lo
            x += w + gap
        bpy.context.view_layer.update()
        save_textures(LIB_DIR)
        (LIB_DIR / 'signage_atlas_layout.json').write_text(json.dumps(
            {'atlas_px': ATLAS_PX, 'px_per_metre': 256, 'uv_rect': '[u0, v0, u1, v1], v up', 'types': atlas_layout()}, indent=1),
            encoding='utf-8')
        palette_image().pack()
        atlas_placeholder_image().pack()
        if not self.only:
            bpy.ops.wm.save_as_mainfile(filepath=str(self.blend_path))
        if not self.args.no_render:
            self.render()
        failed = [k for k, v in out.items() if not v['all_checks_passed']]
        print(f'[SK] {self.id} {rev}: {len(out)} assets, failed: {failed or "none"}')

    # -- previews (Cycles CPU/GPU, not part of the .blend)
    def render(self):
        scene = self.scene
        self.preview_dir.mkdir(parents=True, exist_ok=True)
        studio = bpy.data.collections.new('Studio_NotExported')
        scene.collection.children.link(studio)
        world = bpy.data.worlds.new('Sky')
        scene.world = world
        try:
            world.use_nodes = True
        except Exception:
            pass
        bg = next(n for n in world.node_tree.nodes if n.type == 'BACKGROUND')
        bg.inputs[0].default_value = (*srgb_to_linear((176, 198, 220)), 1)
        bg.inputs[1].default_value = 1.0
        sd = bpy.data.lights.new('Sun', 'SUN')
        sd.energy = 3.4
        sd.angle = math.radians(5)
        sun = bpy.data.objects.new('Sun', sd)
        sv = Vector((math.cos(math.radians(300)), math.sin(math.radians(300)), math.tan(math.radians(50))))
        sun.rotation_euler = (-sv).to_track_quat('-Z', 'Y').to_euler()
        studio.objects.link(sun)
        gm = bpy.data.materials.new('Ground_Studio')
        try:
            gm.use_nodes = True
        except Exception:
            pass
        gb = next(n for n in gm.node_tree.nodes if n.type == 'BSDF_PRINCIPLED')
        gb.inputs['Base Color'].default_value = (*srgb_to_linear((150, 156, 128)), 1)
        gb.inputs['Roughness'].default_value = 1.0
        g = Mesh()
        g.box(400, 400, 0.02, 'concrete', at=(0, 0, -0.011))
        me = bpy.data.meshes.new('Ground')
        me.from_pydata(g.verts, [], g.faces)
        me.materials.append(gm)
        studio.objects.link(bpy.data.objects.new('Ground', me))
        pm = bpy.data.materials.new('Person_Studio')
        pm.diffuse_color = (0.3, 0.3, 0.3, 1)
        try:
            pm.use_nodes = True
            next(n for n in pm.node_tree.nodes if n.type == 'BSDF_PRINCIPLED').inputs['Base Color'].default_value = (0.25, 0.25, 0.28, 1)
        except Exception:
            pass
        person = Mesh()
        person.box(0.5, 0.3, 1.8, 'concrete', base=True)
        me = bpy.data.meshes.new('ScalePerson')
        me.from_pydata(person.verts, [], person.faces)
        me.materials.append(pm)
        pob = bpy.data.objects.new('ScalePerson_0.5x0.3x1.8', me)
        studio.objects.link(pob)
        cam_d = bpy.data.cameras.new('Cam')
        cam = bpy.data.objects.new('Cam', cam_d)
        studio.objects.link(cam)
        scene.camera = cam
        scene.render.engine = 'CYCLES'
        scene.cycles.samples = self.args.samples
        scene.cycles.use_denoising = True
        scene.render.film_transparent = False
        scene.view_settings.view_transform = 'Standard'
        scene.render.image_settings.file_format = 'PNG'

        def frame(objs, az, el, res, lens=50, pad=1.08, fname='x.png', ortho=False):
            bpy.context.view_layer.update()
            pts = [o.matrix_world @ Vector(c) for o in objs for c in o.bound_box]
            centre = sum(pts, Vector()) / len(pts)
            d = Vector((math.cos(math.radians(el)) * math.sin(math.radians(az)), -math.cos(math.radians(el)) * math.cos(math.radians(az)),
                        math.sin(math.radians(el))))
            rot = (-d).to_track_quat('-Z', 'Y')
            right, up = rot @ Vector((1, 0, 0)), rot @ Vector((0, 1, 0))
            xs = [(p - centre).dot(right) for p in pts]
            ys = [(p - centre).dot(up) for p in pts]
            centre = centre + right * (max(xs) + min(xs)) / 2 + up * (max(ys) + min(ys)) / 2
            wext, hext = max(xs) - min(xs), max(ys) - min(ys)
            aspect = res[0] / res[1]
            radius = max((p - centre).length for p in pts)
            cam_d.type = 'ORTHO' if ortho else 'PERSP'
            cam_d.lens = lens
            cam_d.sensor_fit = 'AUTO'
            if ortho:
                cam_d.ortho_scale = max(wext, hext * aspect) * pad
                dist = radius * 3 + 10
            else:
                fov_w = 2 * math.atan(18 / lens) if aspect >= 1 else 2 * math.atan(18 / lens * aspect)
                fov_h = 2 * math.atan(math.tan(fov_w / 2) / aspect)
                dist = max(wext / 2 / math.tan(fov_w / 2), hext / 2 / math.tan(fov_h / 2)) * pad + radius * 0.5
            cam.location = centre + d * dist
            cam.rotation_euler = rot.to_euler()
            cam_d.clip_end = dist * 4 + 50
            scene.render.resolution_x, scene.render.resolution_y = res
            scene.render.filepath = str(self.preview_dir / fname)
            bpy.ops.render.render(write_still=True)

        allobjs = [o for a in self.assets for o in a['objects']]
        pob.location = (-1.0, 1.2, 0)
        frame(allobjs + [pob], 25, 20, (1800, 760), pad=1.04, fname='00_family_lineup.png', ortho=True)
        for i, a in enumerate(self.assets, 1):
            rx = a['root'].location.x
            sz = self.report[a['name']]['size_xyz_m']
            pob.location = (rx + self.report[a['name']]['bounds_min'][0] - 0.6, 0.6, 0)
            show_person = sz[2] < 25
            if not show_person:
                pob.location.z = -50
            frame(a['objects'] + ([pob] if show_person else []), 35, 18, (900, 900), fname=f'{i:02d}_{a["name"]}.png')
